woori-zip/src/components/domains/loan/BackCard.css, woori-zip/src/components/domains/loan/BackCard.js, woori-zip/src/components/domains/loan/BottomCard.css, woori-zip/src/components/domains/loan/BottomCard.js, woori-zip/src/components/domains/loan/CardList.css, woori-zip/src/components/domains/loan/CardList.js, woori-zip/src/components/domains/loan/CheckList.css, woori-zip/src/components/domains/loan/CheckList.js, woori-zip/src/components/domains/loan/Detail.css, woori-zip/src/components/domains/loan/Detail.js, woori-zip/src/components/domains/loan/LoanCheckListPage.js, woori-zip/src/components/domains/loan/LoanDetailPage.js, woori-zip/src/components/domains/loan/LoanRecommendationPage.js, woori-zip/src/components/domains/loan/TrueFalseButton.css, woori-zip/src/components/domains/loan/TrueFalseButton.js, woori-zip/src/components/domains/loan/WideCard.css, woori-zip/src/components/domains/loan/WideCard.js, woori-zip/src/components/domains/loan/WideCardButton.css, woori-zip/src/components/domains/loan/WideCardButton.js
=> [FEAT] 대출페이지 퍼블리싱 #4

.github/workflows/git-push.yaml, build.sh, woori-zip/src/app/api/health-check/route.js
- git-push.yml 구성
- build.sh 추가
- #17 
- 
- 수정이 필요할수 있습니다.
=> [SETTING/#17]: 초기 병합

woori-zip/src/app/loan/loanCheckList/page.js, woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
=> [FEAT]: 404수정 #4

woori-zip/src/app/loan/loanRecommendation/page.js, woori-zip/src/components/domains/loan/loanRecommendation/BackCard.css, woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.css, woori-zip/src/components/domains/loan/loanRecommendation/CardList.css, woori-zip/src/components/domains/loan/loanRecommendation/WideCard.css, woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js, woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.css
=> [FIX] : 대출추천페이지 디자인수정 #4

woori-zip/next.config.mjs, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/user/login/SubmitButton.js
- 지도 페이지 버그 수정
- #38
- 
- 이미지를 S3에서 가져오는 부분과 파일명 수정했습니다.
=> [BUG/#38]: 지도 페이지 버그 수정 

woori-zip/src/components/domains/user/login/LoginPage.js, woori-zip/src/components/domains/user/login/LoginPage.module.css
- LoginPage.js 및 LoginPage.module.css 추가
- #45
- 
-
=> [hotfix/#45] 파일명으로 인한 긴급 추가

woori-zip/src/app/loan/loanCheckList/page.js, woori-zip/src/app/loan/loanDetail/page.js, woori-zip/src/app/loan/loanRecommendation/page.js, woori-zip/src/components/domains/loan/loanCheckList/CheckList.js, woori-zip/src/components/domains/loan/loanCheckList/CheckList.module.css, woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.module.css, woori-zip/src/components/domains/loan/loanDetail/Detail.js, woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
=> [FIX] : 대출상세, 체크리스트 최종 퍼블리싱 #4

woori-zip/src/app/globals.css, woori-zip/src/app/layout.js, woori-zip/src/components/domains/loan/loanRecommendation/CardList.module.css, woori-zip/src/components/domains/main/PropertyCard/PropertyCard.module.css, woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js, woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.module.css, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/map/NavBar.module.css, woori-zip/src/components/domains/map/PropertyList.module.css, woori-zip/src/components/domains/map/RangeSlider.js, woori-zip/src/components/domains/map/RangeSlider.module.css, woori-zip/src/components/domains/map/Sidebar.module.css
- 로그인 및 회원가입 버튼 추가
- 범위 슬라이더 수정
- closed #87 
- 
- 지도페이지 수정입니다.
=> [REFACTOR] 지도 페이지 nav bar 버튼 수정

woori-zip/src/app/api/instance.js, woori-zip/src/app/api/map/houseApi.js, woori-zip/src/components/domains/map/PropertyDetails.module.css, woori-zip/src/components/domains/map/Sidebar.js, woori-zip/src/components/domains/map/Sidebar.module.css
- api 폴더 구조 넣기
- closed #91 
- 
- api는 전부 폴더로 빼두시길 바랍니다.
=> [FEAT] 전페 페이지 API 폴더 #91

woori-zip/src/app/api/instance.js, woori-zip/src/app/api/map/houseApi.js, woori-zip/src/app/map/page.js, woori-zip/src/components/domains/map/CategoryMenu.js, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/map/PropertyList.js
- 지도페이지 API 분리
- closed #95 
- ![API 분리](https://github.com/user-attachments/assets/ee4c05cd-f6cc-47a7-977f-6c40867e1c05)
- API 분리 해놓았습니다.
=> [REFACTOR] 지도 페이지 API 분리 #95

woori-zip/next.config.mjs, woori-zip/src/app/map/page.js, woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js, woori-zip/src/components/domains/map/Latitude.js, woori-zip/src/components/domains/map/MapView.js, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/map/PropertyDetails.js, woori-zip/src/components/domains/map/PropertyList.js
- 메인 페이지, 지도페이지 연결
- closed #97
- 
-
=> [REFACTOR] 메인 페이지 라우터 연결 #97

woori-zip/src/components/domains/user/login/validation.js, woori-zip/src/components/domains/user/register/Register.module.css, woori-zip/src/components/domains/user/register/RegisterPage.js
=> [feat] 가입하기 수정

woori-zip/src/app/api/instance.js, woori-zip/src/app/api/mypage/BookMarkAPI.js
- 마이페이지 북마크 api 수정
- closed #105 
- 
-
=> [feat] 마이페이지 북마크 api 수정

woori-zip/src/app/api/mypage/MypageAPI.js, woori-zip/src/components/domains/mypage/MemberInfo/Member.js, woori-zip/src/components/domains/mypage/MemberInfo/Member.module.css
- 마이페이지 정보 불러오기
- closed #113 
-
=> Feat/#113 마이페이지 정보 불러오기

woori-zip/src/app/api/map/houseApi.js
- 작업한 내용 기술
- closed #121 
- 
- data에서 값을 가져오게 수정하였습니다.
=> [refactor/#121]: api 구조 변경 data안에서 가져오기

woori-zip/src/app/api/manager/managerAPI.js, woori-zip/src/app/manager/page.js, woori-zip/src/components/domains/analysis/analysis/Analysis.module.css, woori-zip/src/components/domains/manager/LoanManagement/LoanView.js, woori-zip/src/components/domains/manager/LoanManagement/LoanView.module.css, woori-zip/src/components/domains/manager/LogManagement/LogSearch.js, woori-zip/src/components/domains/manager/LogManagement/LogSearch.module.css, woori-zip/src/components/domains/manager/Tabs/Tabs.module.css, woori-zip/src/components/domains/manager/userManagement/AgentList/AgentList.js, woori-zip/src/components/domains/manager/userManagement/AgentList/AgentList.module.css, woori-zip/src/components/domains/manager/userManagement/ManagerList/ManagerList.js, woori-zip/src/components/domains/manager/userManagement/ManagerList/ManagerList.module.css, woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.js, woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.module.css
- 사용자 조회 api 연결
- 아이디 조회 api 연결
- 대출상품 조회 api 연결
- closed #109 
- 
-
=> [FEAT] 관리자 페이지 api 연결

woori-zip/src/app/api/mypage/RecentlyLoanListAPI.js, woori-zip/src/app/realestate/page.js, woori-zip/src/components/domains/mypage/Tabs/Tabs.module.css, woori-zip/src/components/domains/mypage/loan/LoanCard.js, woori-zip/src/components/domains/mypage/loan/LoanCard.module.css, woori-zip/src/components/domains/mypage/loan/hooks/useLoan.js, woori-zip/src/components/domains/mypage/loan/loan.js, woori-zip/src/components/domains/mypage/loan/loan.module.css
- 무한 스크롤 적용한 최근 본 대출 조회
- closed #153 
-
=> [FEAT] 무한 스크롤 적용한 최근 본 대출 조회

woori-zip/src/components/domains/user/login/LoginContent.js, woori-zip/src/components/layout/Header/Header.js, woori-zip/src/components/layout/Header/Header.module.css
- 로그인 api 수정
- closed #155 
- 
-
=> [REFACTOR] 로그인 api 수정

woori-zip/src/app/api/agent/UploadedPropertiesAPI.js, woori-zip/src/components/domains/mypage/loan/loan.js, woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.js, woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.module.css, woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.js, woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.module.css, woori-zip/src/components/domains/realsestate/UploadedProperties/hooks/useProperty.js
- 중개사가 올린 집 조회
- closed #157 
-
=> [FEAT] 중개사가 올린 집 조회 #157

woori-zip/src/components/domains/user/onboarding/MockupBox.js
=> [FEAT] 목업 추가

woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
- 최근 본 대출 모바일
- closed #175 
- npm run build
- 마이페이지 최근 본 대출 모바일 css
-
=> [FEAT] 마이페이지 최근 본 대출

woori-zip/.gitignore, woori-zip/cypress.config.js, woori-zip/cypress/e2e/analysis.cy.js, woori-zip/cypress/e2e/home.cy.js, woori-zip/cypress/e2e/login.cy.js, woori-zip/cypress/e2e/map.cy.js, woori-zip/cypress/e2e/mypage.cy.js, woori-zip/cypress/support/e2e.js, woori-zip/package-lock.json, woori-zip/package.json, woori-zip/src/app/api/map/houseApi.js, woori-zip/src/components/domains/map/CategoryMenu.module.css, woori-zip/src/components/domains/map/Latitude.js, woori-zip/src/components/domains/map/MapPageContent.js, woori-zip/src/components/domains/map/MapView.js, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/map/PropertyList.js
- 지도페이지 수정 및 테스트 코드 추가
- closed #188 
- ![빌드](https://github.com/user-attachments/assets/11e6bdc6-d77f-4344-9eaf-c39e815b01c0)
-
=> [FEAT] 지도페이지 수정 및 테스트 코드 추가

woori-zip/.gitignore, woori-zip/cypress.config.js, woori-zip/cypress/e2e/analysis.cy.js, woori-zip/cypress/e2e/home.cy.js, woori-zip/cypress/e2e/login.cy.js, woori-zip/cypress/e2e/map.cy.js, woori-zip/cypress/e2e/mypage.cy.js, woori-zip/cypress/support/e2e.js, woori-zip/package-lock.json, woori-zip/package.json, woori-zip/src/app/api/map/houseApi.js, woori-zip/src/app/api/mypage/MypageAPI.js, woori-zip/src/app/api/mypage/RecentlyLoanListAPI.js, woori-zip/src/auth.js, woori-zip/src/components/domains/main/EnhancedGrid.js, woori-zip/src/components/domains/main/EnhancedGrid.module.css, woori-zip/src/components/domains/map/CategoryMenu.module.css, woori-zip/src/components/domains/map/Latitude.js, woori-zip/src/components/domains/map/MapPageContent.js, woori-zip/src/components/domains/map/MapView.js, woori-zip/src/components/domains/map/NavBar.js, woori-zip/src/components/domains/map/PropertyList.js, woori-zip/src/components/layout/Header/Header.js
- 지도페이지 수정 및 테스트 코드 추가 후 병합
- 
-
=> [MERGE] 지도페이지 수정 및 테스트 코드 추가 후 병합

woori-zip/src/app/api/manager/managerAPI.js, woori-zip/src/components/domains/manager/LogManagement/LogDetail.js, woori-zip/src/components/domains/manager/LogManagement/LogDetail.module.css, woori-zip/src/components/domains/manager/LogManagement/LogSearch.js, woori-zip/src/components/domains/manager/LogManagement/LogSearch.module.css, woori-zip/src/components/domains/manager/LogManagement/Modal.js, woori-zip/src/components/domains/manager/LogManagement/Modal.module.css, woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.js
- 로그 조회, 상세 조회 추가 및 회원 정보 조회 수정
- closed #183
=> [FEAT]: 로그 조회, 상세 조회 추가 및 회원 정보 조회 수정

woori-zip/src/app/api/manager/managerAPI.js, woori-zip/src/components/domains/manager/LoanManagement/LoanView.js, woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.js, woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.module.css, woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.js, woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.module.css, woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.js, woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.module.css, woori-zip/src/components/domains/manager/LoanManagement/modal/EditModal.js, woori-zip/src/components/domains/manager/LoanManagement/modal/EditModal.module.css, woori-zip/src/components/domains/manager/LoanManagement/modal/Modal.js, woori-zip/src/components/domains/manager/LoanManagement/modal/Modal.module.css
- 대출상품관리 수정 하기 초안
- closed #189 
- 
-
=> Feat/#189: 대출상품관리 수정 하기 초안

woori-zip/src/components/domains/loan/loanDetail/Detail.module.css, woori-zip/src/components/domains/mypage/Bookmarks/BookmarkCard.module.css, woori-zip/src/components/domains/mypage/MemberInfo/Member.js, woori-zip/src/components/domains/mypage/MemberInfo/Member.module.css, woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
- 대출 상세, 마이페이지, 북마크 이미지 추가
- closed #200 
- 
-
=> [FEAT] 이미지 추가
